In [1]:
import numpy as np

In [29]:
arr = np.random.randint(1,100,size=10)
print(arr)
sort = np.sort(arr)
print(sort)
arr.sort()
print("Array is sorted in the original one ",arr)

[42  2 29 49 93 70 60 83 87  5]
[ 2  5 29 42 49 60 70 83 87 93]
Array is sorted in the original one  [ 2  5 29 42 49 60 70 83 87 93]


In [39]:
arr = np.random.randint(1,100,size=10)
print(arr)
i=np.argsort(arr)
print(i)
sorted_=arr[i]
print("Sorted via fancy",sorted_)
np.sort(arr)

[10 60 92 54  1 18 58 80 74 58]
[4 0 5 3 6 9 1 8 7 2]
Sorted via fancy [ 1 10 18 54 58 58 60 74 80 92]


array([ 1, 10, 18, 54, 58, 58, 60, 74, 80, 92])

In [47]:
np.random.seed(1)
ar =np.random.randint(19,220,size=(4,6))
print("Original Array",ar)
row_sorted= np.sort(ar,axis=0)
print("Row Sorted",row_sorted)
col_sorted= np.sort(ar,axis=1)
print("col sorted",col_sorted)

Original Array [[ 56 159  91 156 152  98]
 [211 163 148  90 153  44]
 [197  39 120 165 158 175]
 [176 161  69  87 115 105]]
Row Sorted [[ 56  39  69  87 115  44]
 [176 159  91  90 152  98]
 [197 161 120 156 153 105]
 [211 163 148 165 158 175]]
col sorted [[ 56  91  98 152 156 159]
 [ 44  90 148 153 163 211]
 [ 39 120 158 165 175 197]
 [ 69  87 105 115 161 176]]


In [61]:
np.random.seed(1)
ar =np.random.randint(1,22,size=15)
print(ar)
a1=np.partition(ar, 4)
print("3 smallest ",a1)
np.sort(ar)

[ 6 12 13  9 10 12  6 16  1 17  2 13  8 14  7]
3 smallest  [ 6  6  2  1  7 12 10 12  9 17 13 13  8 14 16]


array([ 1,  2,  6,  6,  7,  8,  9, 10, 12, 12, 13, 13, 14, 16, 17])

In [71]:
stud_name = np.array(["Jawwad","Ali","Farooqui"])
print(len(stud_name))
scores=np.array([24,35,11])
a=np.argsort(scores)
ranked_stud=stud_name[a]
print(ranked_stud)


3
['Farooqui' 'Jawwad' 'Ali']


In [75]:
np.random.seed(1)
ar =np.random.randint(19,220,size=(10,2))
print(ar)

[[ 56 159]
 [ 91 156]
 [152  98]
 [211 163]
 [148  90]
 [153  44]
 [197  39]
 [120 165]
 [158 175]
 [176 161]]
